# scrutinizer-ci.com configuration
imports:
  - javascript
  - php
filter:
  excluded_paths:
    - build/
    - node_modules/
    - public/js/
    - tmp/
    - vendor/
    - tests/doctum-config.php
checks:
  javascript: true
  php: true
tools:
  external_code_coverage:
    runs: 4 # php 7.x versions
    timeout: 900 # 15 min
build:
  image: default-jammy # New NodeJS versions require newer versions of glibc (noble was not available on 12/09/2025)
  nodes:
    analysis:
      environment:
        php: 8.2
        node: 20 # Scrutinizer uses nvm
      dependencies:
        before:
          - composer config --unset repositories.0
          - composer install
          - composer require tecnickcom/tcpdf pragmarx/google2fa-qrcode bacon/bacon-qr-code code-lts/u2f-php-server
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run
