name: Lint php documentation

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - QA_**

jobs:
    lint-docs:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Lint phpdoc blocks
              uses: sudo-bot/action-doctum@v5
              with:
                  config-file: test/doctum-config.php
                  method: "parse"
                  cli-args: "--output-format=github --no-ansi --no-progress -v --ignore-parse-errors"
