name: Check other tools and scripts

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - QA_**

permissions:
  contents: read

jobs:
  build-documentation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Sphinx for the documentation build
        run: |
          sudo apt-get update
          sudo apt-get install -y sphinx-doc python3-sphinx

      - name: Build the documentation
        run: make -C docs html SPHINXOPTS='-n -W -a'

  build-release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: ["8.2"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install gettext
        run: sudo apt-get install -y gettext

      - name: Set up PHP ${{ matrix.php-version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: mbstring, iconv, mysqli, zip, gd
          tools: composer:v2

      - name: Install Composer dependencies
        uses: ramsey/composer-install@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Sphinx for the documentation build
        run: pip install 'Sphinx'

      - name: Build the release
        run: ./bin/internal/create-release.sh --ci
