name: Run tests

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master
      - QA_**

jobs:
    test-php:
        name: Test on php ${{ matrix.php-version }} and ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                php-version: ["7.1", "7.2", "7.3", "7.4", "8.0"]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Install gettext
              run: sudo apt-get install -y gettext
            - name: Generate mo files
              run: ./scripts/generate-mo --quiet
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, iconv, mysqli, zip, gd
                  coverage: xdebug
                  tools: composer:v2
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              if: ${{ matrix.php-version != '8.0' }}
              run: composer install --no-interaction
            - name: Install dependencies for php 8.0
              if: ${{ matrix.php-version == '8.0' }}
              run: composer install --no-interaction --ignore-platform-reqs
            - name: Run php tests
              run: composer run phpunit --  --exclude-group selenium
            - name: Send coverage
              uses: codecov/codecov-action@v1
              with:
                flags: unit-${{ matrix.php-version }}-${{ matrix.os }}
                name: phpunit-${{ matrix.php-version }}-${{ matrix.os }}
            - name: Send coverage to Scrutinizer
              uses: sudo-bot/action-scrutinizer@latest
              # Upload can fail on forks
              continue-on-error: true
              with:
                  cli-args: "--format=php-clover build/logs/clover.xml"
            - name: Send coverage to Codacy
              # Upload can fail on forks or if the secret is missing
              continue-on-error: true
              uses: codacy/codacy-coverage-reporter-action@master
              with:
                project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                coverage-reports: build/logs/clover.xml

    test-php-dbase:
        name: Test on php ${{ matrix.php-version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        strategy:
            matrix:
                php-version: ["7.1"]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Install gettext
              run: sudo apt-get install -y gettext
            - name: Generate mo files
              run: ./scripts/generate-mo --quiet
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: dbase, mbstring, iconv, mysqli, zip, gd
                  coverage: xdebug
                  tools: composer:v2
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              run: composer install
            - name: Run php tests
              run: composer run phpunit --  --exclude-group selenium
            - name: Send coverage
              uses: codecov/codecov-action@v1
              with:
                flags: dbase-extension
                name: php-7.1-dbase-enabled
            - name: Send coverage to Scrutinizer
              uses: sudo-bot/action-scrutinizer@latest
              # Upload can fail on forks
              continue-on-error: true
              with:
                  cli-args: "--format=php-clover build/logs/clover.xml"
            - name: Send coverage to Codacy
              # Upload can fail on forks or if the secret is missing
              continue-on-error: true
              uses: codacy/codacy-coverage-reporter-action@master
              with:
                project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                coverage-reports: build/logs/clover.xml

    test-php-recode:
        name: Test on php ${{ matrix.php-version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        strategy:
            matrix:
                php-version: ["7.1"]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Install gettext
              run: sudo apt-get install -y gettext
            - name: Generate mo files
              run: ./scripts/generate-mo --quiet
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: recode, mbstring, iconv, mysqli, zip, gd
                  coverage: xdebug
                  tools: composer:v2
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              run: composer install
            - name: Run php tests
              run: composer run phpunit --  --exclude-group selenium
            - name: Send coverage
              uses: codecov/codecov-action@v1
              with:
                flags: recode-extension
                name: php-7.1-recode-enabled
            - name: Send coverage to Scrutinizer
              uses: sudo-bot/action-scrutinizer@latest
              # Upload can fail on forks
              continue-on-error: true
              with:
                  cli-args: "--format=php-clover build/logs/clover.xml"
            - name: Send coverage to Codacy
              # Upload can fail on forks or if the secret is missing
              continue-on-error: true
              uses: codacy/codacy-coverage-reporter-action@master
              with:
                project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
                coverage-reports: build/logs/clover.xml

    test-php-random:
        name: Test on php ${{ matrix.php-version }} and ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        if: "!contains(github.event.head_commit.message, '[ci skip]')"
        strategy:
            matrix:
                php-version: ["7.4"]
                os: [ubuntu-latest]
        steps:
            - uses: actions/checkout@v2
            - name: Install gettext
              run: sudo apt-get install -y gettext
            - name: Generate mo files
              run: ./scripts/generate-mo --quiet
            - name: Use php ${{ matrix.php-version }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-version }}
                  extensions: mbstring, iconv, mysqli, zip, gd
                  tools: composer:v2
            - name: Cache module
              uses: actions/cache@v2
              with:
                  path: ~/.composer/cache/
                  key: composer-cache
            - name: Install dependencies
              run: composer install
            - name: Run php tests
              # This one is allowed to fail, but we hope it will not
              continue-on-error: true
              run: composer run phpunit --  --exclude-group selenium --order-by=random --stop-on-failure
